server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/equipmentloansystem?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# Custom configuration if needed
